CREATE DATABASE IF NOT EXISTS ecotrack;
USE ecotrack;

CREATE TABLE IF NOT EXISTS reports (
  id INT AUTO_INCREMENT PRIMARY KEY,
  location VARCHAR(150) NOT NULL,
  waste_type VARCHAR(50) NOT NULL,
  status ENUM('Pending', 'In Progress', 'Cleaned') NOT NULL DEFAULT 'Pending',
  description TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
